// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cadeMedicoApi.Data;

namespace cadeMedicoApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210212013452_inital")]
    partial class inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("cadeMedicoApi.Models.CidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "PR",
                            Nome = "Apucarana"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "PR",
                            Nome = "Lodrina"
                        },
                        new
                        {
                            Id = 3,
                            Estado = "PR",
                            Nome = "Maringa"
                        },
                        new
                        {
                            Id = 4,
                            Estado = "SP",
                            Nome = "São Paulo"
                        },
                        new
                        {
                            Id = 5,
                            Estado = "RJ",
                            Nome = "Rio de Janeiro"
                        });
                });

            modelBuilder.Entity("cadeMedicoApi.Models.EspecialidadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ortopedia"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Podologia"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Otorrinolaringologia"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Pediatria"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Geral"
                        });
                });

            modelBuilder.Entity("cadeMedicoApi.Models.MedicoCidade", b =>
                {
                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CidadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicoId", "CidadeId");

                    b.HasIndex("CidadeId");

                    b.ToTable("MedicoCidade");

                    b.HasData(
                        new
                        {
                            MedicoId = 1,
                            CidadeId = 1
                        },
                        new
                        {
                            MedicoId = 2,
                            CidadeId = 3
                        },
                        new
                        {
                            MedicoId = 3,
                            CidadeId = 3
                        },
                        new
                        {
                            MedicoId = 4,
                            CidadeId = 4
                        },
                        new
                        {
                            MedicoId = 5,
                            CidadeId = 5
                        });
                });

            modelBuilder.Entity("cadeMedicoApi.Models.MedicoEspecialidade", b =>
                {
                    b.Property<int>("MedicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicoId", "EspecialidadeId");

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("MedicoEspecialidade");

                    b.HasData(
                        new
                        {
                            MedicoId = 1,
                            EspecialidadeId = 1
                        },
                        new
                        {
                            MedicoId = 2,
                            EspecialidadeId = 3
                        },
                        new
                        {
                            MedicoId = 3,
                            EspecialidadeId = 3
                        },
                        new
                        {
                            MedicoId = 4,
                            EspecialidadeId = 4
                        },
                        new
                        {
                            MedicoId = 5,
                            EspecialidadeId = 5
                        });
                });

            modelBuilder.Entity("cadeMedicoApi.Models.MedicoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Crm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crm = "323440",
                            Nome = "Luiz",
                            Telefone = "900999"
                        },
                        new
                        {
                            Id = 2,
                            Crm = "434440",
                            Nome = "Joao",
                            Telefone = "912999"
                        },
                        new
                        {
                            Id = 3,
                            Crm = "6464440",
                            Nome = "Clyetin",
                            Telefone = "932999"
                        },
                        new
                        {
                            Id = 4,
                            Crm = "756440",
                            Nome = "Jorgin",
                            Telefone = "944999"
                        },
                        new
                        {
                            Id = 5,
                            Crm = "756440",
                            Nome = "Joana",
                            Telefone = "953999"
                        });
                });

            modelBuilder.Entity("cadeMedicoApi.Models.PrivilegioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Privilegios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "MASTER"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "ADM"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "USER"
                        });
                });

            modelBuilder.Entity("cadeMedicoApi.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrivilegioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "Suroki",
                            Nome = "Luiz",
                            PrivilegioId = 1,
                            Senha = "123"
                        },
                        new
                        {
                            Id = 2,
                            Login = "Jao",
                            Nome = "João",
                            PrivilegioId = 2,
                            Senha = "123"
                        },
                        new
                        {
                            Id = 3,
                            Login = "jota",
                            Nome = "Joana",
                            PrivilegioId = 1,
                            Senha = "123"
                        },
                        new
                        {
                            Id = 4,
                            Login = "Fonseca",
                            Nome = "Cloves",
                            PrivilegioId = 1,
                            Senha = "123"
                        },
                        new
                        {
                            Id = 5,
                            Login = "Knwood",
                            Nome = "Marcelo",
                            PrivilegioId = 3,
                            Senha = "123"
                        });
                });

            modelBuilder.Entity("cadeMedicoApi.Models.MedicoCidade", b =>
                {
                    b.HasOne("cadeMedicoApi.Models.CidadeModel", "Cidade")
                        .WithMany("MedicoCidade")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cadeMedicoApi.Models.MedicoModel", "Medico")
                        .WithMany("MedicoCidade")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("cadeMedicoApi.Models.MedicoEspecialidade", b =>
                {
                    b.HasOne("cadeMedicoApi.Models.EspecialidadeModel", "Especialidade")
                        .WithMany("MedicoEspecialidade")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cadeMedicoApi.Models.MedicoModel", "Medico")
                        .WithMany("MedicoEspecialidade")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("cadeMedicoApi.Models.CidadeModel", b =>
                {
                    b.Navigation("MedicoCidade");
                });

            modelBuilder.Entity("cadeMedicoApi.Models.EspecialidadeModel", b =>
                {
                    b.Navigation("MedicoEspecialidade");
                });

            modelBuilder.Entity("cadeMedicoApi.Models.MedicoModel", b =>
                {
                    b.Navigation("MedicoCidade");

                    b.Navigation("MedicoEspecialidade");
                });
#pragma warning restore 612, 618
        }
    }
}
